---
- name: download Oracle JDK7 to host
  local_action: >
    command wget -N -P "{{oracle_jdk_download_dir}}" --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/{{oracle_jdk_package_subdir}}/{{oracle_jdk_package}}
  tags: download

- name: "{{oracle_jdk_instalation_dir}} must exist"
  file:
    path="{{oracle_jdk_instalation_dir}}"
    state="directory"

- name: unpacks Jdk7
  unarchive:
    src="{{oracle_jdk_download_dir}}/{{oracle_jdk_package}}"
    dest="{{oracle_jdk_instalation_dir}}"
    creates="{{oracle_jdk_instalation_dir}}/jdk{{oracle_jdk_version}}/bin/java"
    force=no
  tags: unpack

- name: setup JAVA_HOME
  lineinfile:
    dest=~/.bashrc
    line="export JAVA_HOME={{oracle_jdk_instalation_dir}}/jdk{{oracle_jdk_version}}"
    state=present
    insertafter=EOF
    create=true

- name: append JAVA_HOME to PATH
  lineinfile:
    dest=~/.bashrc
    line="export PATH=$JAVA_HOME/bin:$PATH"
    state=present
    insertafter=EOF
    create=true
